# Линейная алгебра

Для лучшей читаемости следует отключить научную нотацию

In [ ]:
import numpy as np
np.set_printoptions(suppress=True)

In [15]:
import numpy as np
np.set_printoptions(suppress=True)
data = {
    "years": [1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980],
    "consumption": [737.1, 812.0, 808.1, 976.4, 1084.3, 1204.4, 1346.5, 1507.2, 1667.2],
    "gnp": [1185.9, 1326.4, 1434.2, 1549.2, 1718.0, 1918.3, 2163.9, 2417.8, 2633.1],
    "deflator": [1.0000, 1.0575, 1.1508, 1.2579, 1.3234, 1.4005, 1.5042, 1.6342, 1.7864],
    "discount_rate": [4.50, 6.44, 7.83, 6.25, 5.50, 5.46, 7.46, 10.28, 11.77]
}
data = np.array(list(data.values()))
data

array([[1972.    , 1973.    , 1974.    , 1975.    , 1976.    , 1977.    ,
        1978.    , 1979.    , 1980.    ],
       [ 737.1   ,  812.    ,  808.1   ,  976.4   , 1084.3   , 1204.4   ,
        1346.5   , 1507.2   , 1667.2   ],
       [1185.9   , 1326.4   , 1434.2   , 1549.2   , 1718.    , 1918.3   ,
        2163.9   , 2417.8   , 2633.1   ],
       [   1.    ,    1.0575,    1.1508,    1.2579,    1.3234,    1.4005,
           1.5042,    1.6342,    1.7864],
       [   4.5   ,    6.44  ,    7.83  ,    6.25  ,    5.5   ,    5.46  ,
           7.46  ,   10.28  ,   11.77  ]])

In [19]:
data.T.T.T

array([[1972.    ,  737.1   , 1185.9   ,    1.    ,    4.5   ],
       [1973.    ,  812.    , 1326.4   ,    1.0575,    6.44  ],
       [1974.    ,  808.1   , 1434.2   ,    1.1508,    7.83  ],
       [1975.    ,  976.4   , 1549.2   ,    1.2579,    6.25  ],
       [1976.    , 1084.3   , 1718.    ,    1.3234,    5.5   ],
       [1977.    , 1204.4   , 1918.3   ,    1.4005,    5.46  ],
       [1978.    , 1346.5   , 2163.9   ,    1.5042,    7.46  ],
       [1979.    , 1507.2   , 2417.8   ,    1.6342,   10.28  ],
       [1980.    , 1667.2   , 2633.1   ,    1.7864,   11.77  ]])

In [25]:
cons = data.T[:,1]
x = data.T[:,2:]

In [26]:
cons

array([ 737.1,  812. ,  808.1,  976.4, 1084.3, 1204.4, 1346.5, 1507.2,
       1667.2])

In [31]:
x.T @ x

array([[31715480.6       ,    23057.84137   ,   126703.035     ],
       [   23057.84137   ,       16.86219935,       92.155205  ],
       [  126703.035     ,       92.155205  ,      522.0195    ]])